version: '3'

services:
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles
    networks:
      - scaffolding-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-scaffolding:assessment
    env_file: local.env
    command: >
      /bin/ash -c "
        flask run --host=0.0.0.0
      "
    volumes:
      - ./src/:/code
      - ./logs:/var/log/scaffolding
    ports:
      - "8400:5000"
    depends_on:
      - db
    networks:
      - scaffolding-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-scaffolding:assessment
    env_file: local.env
    command: >
      /bin/ash -c "
        celery -A app worker --loglevel INFO
      "
    volumes:
      - ./src/:/code
      - ./logs:/var/log/scaffolding
    depends_on:
      - db
    networks:
      - scaffolding-network

networks:
  scaffolding-network:
